### ISSUE TITLE
希望Text类型的文章能支持富文本格式

### ISSUE THREAD

**Issue by ismlsmile** [thinkry/wecode#12]
没找到选项，不知道这功能是否已经包含？

**Comment by thinkry** [comment]
wecode的编辑器使用的是scintilla，它支持多种编程语言的语法高亮，但不支持富文本编辑，比富文本有优势的地方是不用太关注格式，更关注内容，便捷高效。

**Comment by ismlsmile** [comment]
能否在点击左边树上节点的时候判断下节点类型，如果是代码类型就用原来的scintilla，如果是Text类型，则切换到一个支持富文本编辑的控件

**Comment by thinkry** [comment]
这个建议不错，记下了。我的QQ是19805896，有兴趣加我QQ哈。
