### ISSUE TITLE
建议:添加全文搜索功能

### ISSUE THREAD

**Issue by linhucong110** [thinkry/wecode#13]
目前只能对标题进行搜索, 这样查找内容时会很不方便.内容多了之后查找效果比较差. 希望加入对标题及内容的模糊查找, 这样可以方便的搜索到需要的内容,谢谢!

**Comment by thinkry** [comment]
在1.1.6版本已实现全文搜索。注意下：云笔记模式下的全文搜索是搜索本地缓存，如果在多处使用wecode，需要在搜索前执行下“云笔记同步到本地”
