### ISSUE TITLE
存在bug

### ISSUE THREAD

**Issue by jimersylee** [thinkry/wecode#14]
不能使用谷歌输入法输入中文

**Comment by thinkry** [comment]
我测试了谷歌拼音2.7.25.128版本，发现是可以的。你的是啥情况？或者加我QQ直接聊 19805896

**Comment by jimersylee** [comment]
之前用的2.7.24版本 升级了就好了~

------------------ 原始邮件 ------------------
发件人: "thinkry"notifications@github.com; 
发送时间: 2014年11月11日(星期二) 上午9:46
收件人: "thinkry/wecode"wecode@noreply.github.com; 
抄送: "jimersylee"jimersylee@gmail.com; 
主题: Re: [wecode] 存在bug (#14)

我测试了谷歌拼音2.7.25.128版本，发现是可以的。你的是啥情况？或者加我QQ直接聊 19805896

**Comment by thinkry** [comment]
OK
