### ISSUE TITLE
云笔记同步后换行全没了

### ISSUE THREAD

**Issue by banbo** [thinkry/wecode#18]
云笔记同步后换行全没了，所有文字都缩到一行了。

**Comment by banbo** [comment]
比如输入：
1.
2.
3.
4.
5.

同步后再打开文件，文件变成了：
1. 2. 3. 4. 5. 

换行没有了！

希望老大能看看是什么原因，尽快修正一下，非常喜欢wecode！

**Comment by renzhiliang** [comment]
这个问题确实很让人恼火，希望有人解决一下！

**Comment by thinkry** [comment]
这个问题是有道云把wecode提交的内容过滤了换行导致的。在今天发布的1.1.7里解决了此问题，但之前被吞噬的换行无法找回了。。。
