### ISSUE TITLE
云笔记无法同步到本地

### ISSUE THREAD

**Issue by loliconer** [thinkry/wecode#20]
建立云笔记后，一开始点击云笔记同步到本地没反应，后来多点几次后程序直接崩溃退出。最后所有的云笔记都打不开了。

**Comment by loliconer** [comment]
![2015-05-08_005045](https://cloud.githubusercontent.com/assets/9247561/7520836/4fa1c7cc-f51c-11e4-8450-e38b6eed16a9.jpg)

**Comment by thinkry** [comment]
在今天发布的1.1.7里修复了此bug，如此问题还有遇到，欢迎反馈下
