### ISSUE TITLE
同步问题

### ISSUE THREAD

**Issue by renzhiliang** [thinkry/wecode#22]
删掉“云笔记本”的内容，“本地笔记本”的内容也找不见了，咋用？

**Comment by renzhiliang** [comment]
“云笔记本”为空，新建“本地笔记本”内容，同步后“本地笔记本”也为空了。同步不是把最新修改的内容更新吗？

**Comment by renzhiliang** [comment]
现在是用“云笔记本”的话，因为格式混乱根本不敢用。但是不用“云笔记本”用“本地笔记本”的话，又不能点同步，一同步就连本地的都同步没了。这云功能做的，简直起了反作用了

**Comment by thinkry** [comment]
格式混乱的问题，这周内争取解决掉。感谢支持！

**Comment by herbert2008** [comment]
最近正在进行修改，原因是网易近期调整了云笔记功能以及相关API，之前云笔记中的换行符被有道给直接去掉了，导致文档格式混乱，所以恐怕之前保存的云笔记格式无法恢复，非常抱歉，但是如果没有同步过到本地的话还是可以打开本地缓存笔记的。
另外这周我争取修复相关BUG，发布下一个版本，感谢大家的支持，再次对大家说声抱歉。

**Comment by banbo** [comment]
加油，我天天关注着呢 @herbert2008

**Comment by thinkry** [comment]
今天发布的1.1.7问题重点解决了2个问题，有道云文章的换行丢失，以及同步到本地时可能会崩溃。
