### ISSUE TITLE
有道云登录不上

### ISSUE THREAD

**Issue by wenhj1993** [thinkry/wecode#47]
创建云笔记后报出打开失败，重复创建几次都是这样，退出有道云账号后就登录不上有道云了，总是提示无法下载problem,但是在网页直接登录有道云账号是可以登录的

**Comment by thinkry** [comment]
已经联系有道云笔记开放平台，修改了我们应用的回调地址，目前新版本1.1.9版本能够正常登录有道云笔记了。
